spring.application.name=Stationery_shop
# Database URL and credentials
#spring.datasource.url=jdbc:mysql://localhost:3306/stationery_shop?useSSL=false&serverTimezone=UTC
#spring.datasource.username=stationery_shop_user
#spring.datasource.password=29042004
