spring.application.name=Stationery_shop
# Database URL and credentials
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ttthinh2904@gmail.com
spring.mail.password=cjhy myjp nagb xcdy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

#spring.security.enabled=false
jwt.secret=ze33aw4dCBq7Oe4AX89NMWO4OwWZbMVKKpWjxrPiPDVT+U7VocRRmFjCgm3P0Ey6

#google.client-id=98017329848-h17etmll293ebhilpo9ijjsne7qqjprs.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-id=98017329848-h17etmll293ebhilpo9ijjsne7qqjprs.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile

spring.data.redis.host=localhost
spring.data.redis.port=6382

spring.cache.type=redis

# application.properties
cloudinary.cloud-name=dn24cb7q9
cloudinary.api-key=752915646486454
cloudinary.api-secret=quy-vyxjD0aO_poGcBnFDaNsTW8
cloudinary.image-width=1000
cloudinary.image-height=1000
